(define (loadtmp) (load "tmp.scm"))
;; Test for do
;; (let ((x '(1 3 5 7 9)))
;;   (display x)
;;   (newline)
;;   (do ((x x (begin (display "X:")
;;                    (display x)
;;                    (newline)
;;                    (cdr x)))
;;        (sum 0 (begin (display "Sum:")
;;                             (display sum)
;;                             (newline)
;;                             (+ sum (car x)))))
;;       ((null? x) (display "After termination...")
;;        (display "\nFinal Result is ")
;;        (display sum)
;;        (newline)
;;        sum)
;;     (display "Everag Stage:")
;;               (display x)
;;               (display "\t")
;;               (display sum)
;;               (newline)))
